### ISSUE TITLE
Unable to run clasp in a Docker container. 

### ISSUE THREAD

**Issue by chris-garrett** [google/clasp#296]
## Expected Behavior

I should be able to run clasp in a docker container. 

## Actual Behavior

Unable to authenticate as localhost service is listening on a random port. 

## Steps to Reproduce the Problem

  1. docker-compose.yml
```
version: '2'

services:

  svc_gsuite:
    image: chrisgarrett/node-dev:8.2.1
    command: npm run up
    volumes:
    - ./src:/work/app
    - ~/.clasprc.json:/home/node/.clasprc.json
```
  2. `up` script entry in package.json:
```
"up": "yarn install && npx clasp login && npm run watch",
```
  3. copy link in and paste into browser. 
  4. redirection fails because port is random. 

## Specifications

  - Node version (`node -v`): 8.2.1
  - Version (`clasp -v`): 1.5.3
  - OS (Mac/Linux/Windows): alpine 3.6

## Options
  1. Use an environment variable to specify port. 
This feels pretty natural as there are many node examples where this is used. I have this working already in my fork 
  1. Add an argument to `login` to specify the port. 

Thoughts?

I will submit a PR for either of these after some feedback.
